version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 490971871466.dkr.ecr.us-east-1.amazonaws.com
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - docker build -t satya_pv_rep .
      - docker tag satya_pv_rep:latest 490971871466.dkr.ecr.us-east-1.amazonaws.com/satya_pv_rep:latest
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - docker push 490971871466.dkr.ecr.us-east-1.amazonaws.com/satya_pv_rep:latest
